apps/account/urls.py
from django.urls import path

from apps.account.views import SubscribeView, FeedView, LoginView

app_name = "account"
urlpatterns = [
    path('subcribe/', SubscribeView.as_view(), name="subscribe"),
    path('feed/', FeedView.as_view(), name="feed"),
    path('login/', LoginView.as_view(), name="login"),
]

apps/article/urls.py
from django.urls import path

from apps.article.views import HomeView, CategoryView, ArticleView, TagView

app_name = 'article'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('category/<pk>/', CategoryView.as_view(), name="category"),
    path('article/<pk>/', ArticleView.as_view(), name="article-detail"),
    path('tags/<pk>/', TagView.as_view(), name="tag"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.article.urls', 'article')),
    path('account/', include('apps.account.urls', 'account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>NewsTheme</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="{% static 'ie.css' %}" /><![endif]-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<!-- BEGIN navigation -->
<div id="navigation">
        <div class="wrapper">
        <ul style="margin-top: -16px;">
            <li><a href="{% url 'article:home' %}">Home</a></li>
            <li><a href="article/about.html">About Us</a></li>
            <li><a href="article/page.html">Demo Page</a></li>
            <li><a href="{% url 'account:feed' %}">Contact Page</a></li>
        </ul>
        <form method="post">
            {% csrf_token %}
            <input name="search" type="text" {% if search %} value="{{ search }}" {% endif %}/>
            <button type="submit">Search</button>
        </form>
    </div>
</div>
<div class="wrapper">
    <div id="header">
        <h1><a href="#">NewsTheme</a></h1>
        <div class="ad468x60"><a href="#"><img src="images/ad468x60.gif" alt=""/></a></div>
    </div>
</div>
{% block content %}


{% endblock %}

<div id="footer">
    <div class="wrapper">
        <p class="l">Copyright &copy; 2009 - <a href="#">Website Name</a> &middot; All Rights Reserved</p>
        <p class="r">Template by: <a href="http://www.wpthemedesigner.com/">WordPress Designer</a> | Get More <a
                href="#">Free CSS Templates</a></p>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>
</html>

templates/sidebar.html
{% load static %}
{% load i18n %}
{% load l10n %}
<div id="sidebar">
    <div class="row">
        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
            <select class="form-control form-control-sm" id="exampleFormControlSelect1" name="language"
                    onchange="this.form.submit();">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
        </form>
    </div>
    <div class="row">
        <h5>Meta</h5>
        <ul>
            <li><a href="{% url 'account:login' %}">Login</a></li>
            <li><a href="{% url 'account:subscribe' %}">Register</a></li>
        </ul>
        <!-- end meta -->

    </div>

    <!-- begin Advertisement -->
    <div class="row">

        <div class="ads">
            <div class="col-12">
                <a href="#"><img src="{% static 'images/ad125x125.jpg' %}" alt=""/></a>
                <a href="#"><img src="{% static 'images/ad125x125.jpg' %}" alt=""/></a>
            </div>
            <a href="#"><img src="{% static 'images/ad125x125.jpg' %}" alt=""/></a>
            <a href="#"><img src="{% static 'images/ad125x125.jpg' %}" alt=""/></a>
        </div>
    </div>
    <!-- end Advertisement -->
    <!-- begin subscribe -->
    <div class="row">
        <h5>
            {% trans 'Subscribe Here' %}
        </h5>
        <form class="subscribe" method="post" action="{% url 'account:subscribe' %}">
            {% csrf_token %}
            <a href="{% url 'account:subscribe' %}">Subscribe via RSS Feed or</a>
            <button type="submit">subcribe</button>
        </form>

    </div>
    <!-- end subscribe -->
    <div class="row">
        <div class="row">
            <h5>Popular Posts</h5>
            <ul>
                <li><a href="#">Make Money Online Creating Websites</a></li>
                <li><a href="#">Top 100 Internet Marketing Tips</a></li>
                <li><a href="#">Tutorial: How to add Videos in your Post</a></li>
                <li><a href="#">Sample Post Unordered List</a></li>
                <li><a href="#">Sample Post Blockquote</a></li>
            </ul>

        </div>

    </div>
    <!-- begin popular posts -->
    <!-- end popular posts -->
    <div class="row">
        <h5>Tags</h5>
        <ul>
            {% for tag in tags %}
                <li><a href="{% url 'article:tag' pk=tag.id%}">{{ tag.name }}</a></li>
            {% endfor %}

        </ul>

        <div class="tags"></div>
        <!-- end tags -->
        <!-- begin tags -->
    </div>
    <div class="row">
        <!-- BEGIN left -->
        <div class="l">
            <!-- begin categories -->
            <h5>Categories</h5>
            <ul style="padding: 0; margin: 0">
                {% for category in categories %}
                    <li><a href="{% url 'article:category' category.id %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
            <!-- end categories -->
        </div>
        <div class="r">
            <!-- begin archives -->
            <h5>Archives</h5>
            <ul style="padding: 0; margin: 0">
                <li><a href="#">August 2008</a></li>
                <li><a href="#">July 2008</a></li>
                <li><a href="#">June 2008</a></li>
                <li><a href="#">May 2008</a></li>
                <li><a href="#">April 2008</a></li>
                <li><a href="#">March 2008</a></li>
            </ul>
            <!-- end archives -->

        </div>

    </div>            <!-- begin pages -->
    <div class="row">
        <div class="l">
            <h5>Pages</h5>
            <ul style="padding: 0; margin: 0">
                <li><a href="{% url 'article:home'%}">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Archives</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="{% url 'account:feed' %}">Contact</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="r">
            <h5>Blogroll</h5>
            <ul style="padding: 0; margin: 0">
                <li><a href="#">Carlos</a></li>
                <li><a href="#">Digital Point Forum</a></li>
                <li><a href="#">Eric's Photo Gallery</a></li>
                <li><a href="#">Fashion Trends</a></li>
                <li><a href="#">Google Scoreboard</a></li>
                <li><a href="#">Marketing Forum</a></li>
            </ul>

        </div>
    </div>
    <!-- end pages -->
</div>