apps/article/urls.py
from django.urls import path

from apps.article.views import HomeView, CategoryView, ArticleView, TagView

app_name = 'article'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('category/<pk>/', CategoryView.as_view(), name="category"),
    path('article/<pk>/', ArticleView.as_view(), name="article-detail"),
    path('tags/<pk>/', TagView.as_view(), name="tag"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.article.urls', 'article')),
    path('account/', include('apps.account.urls', 'account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/article/models.py
from datetime import timedelta

from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import CharField, SlugField, TextField, DateTimeField, TextChoices, Manager, ForeignKey, CASCADE, \
    IntegerField, ImageField, SET_NULL, URLField, BooleanField, ManyToManyField
from django.utils import timezone
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField

from apps.article.choices import Status
from apps.article.managers import PublishManager, ActiveAdvertiseManager
from apps.shared.models import BaseModel
from django.utils.translation import gettext_lazy as _

from config import settings


class Article(BaseModel):
    # managers
    objects = Manager()
    published = PublishManager()

    # fields
    title = CharField(verbose_name=_("Title"), max_length=256)
    slug = SlugField(verbose_name=_("SLG"), unique=True, blank=True, max_length=256)
    body = RichTextUploadingField(verbose_name=_("Body"))
    published_at = DateTimeField(verbose_name=_("published"), default=timezone.now)
    status = CharField(verbose_name=_("Status"), max_length=15, choices=Status.choices, default=Status.DRAFT)
    category = ForeignKey(verbose_name=_("Category"), to="article.Category", on_delete=CASCADE,
                          related_name='artcicles')
    likes = IntegerField(verbose_name=_("Likes"), default=0)
    owner = ForeignKey(verbose_name=_("Owner"), to="account.Account", on_delete=SET_NULL, related_name='article',
                       null=True)
    is_active = BooleanField(verbose_name=_("Is Active"), default=False)
    tags = ManyToManyField(verbose_name=_("Tags"), to="article.Tag", related_name="articles")

    def translate_to_eng(self, s: str) -> str:
        d = {
            'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
            'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y',
            'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p',
            'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h',
            'ц': 'c', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y',
            'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya'
        }

        return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        for lang_code, _ in settings.LANGUAGES:

            title_translated = getattr(self, f'title_{lang_code}', None)

            if title_translated:
                if lang_code == "ru":
                    slug_translated = slugify(
                        f"{self.published_at.strftime('%Y-%m-%d')} {self.translate_to_eng(title_translated)}")
                else:
                    slug_translated = slugify(f"{self.published_at.strftime('%Y-%m-%d')} {title_translated}")
                setattr(self, f'slug_{lang_code}', slug_translated)

        super().save(force_insert, force_update, using, update_fields)


    def __str__(self):
        return self.title


class Category(BaseModel):
    name = CharField(max_length=64)

    class Meta:
        verbose_name_plural="Categories"

    def __str__(self):
        return self.name


class Comment(BaseModel):
    body = TextField()
    owner = ForeignKey("account.Account", CASCADE, "comments")
    article = ForeignKey("article.Article", CASCADE, "comments")


def advertise_expire(*args, **kwargs):
    return timezone.now()+timedelta(days=3)


class Advertise(BaseModel):
    objects = Manager()
    active = ActiveAdvertiseManager()

    image = ImageField(upload_to="advertise/images/")
    url = URLField()
    expire_date = DateTimeField(default=advertise_expire)
    phone = PhoneNumberField(region="UZ")
    is_active = BooleanField()

    def __str__(self):
        return self.url


class Tag(BaseModel):
    name = CharField(max_length=56)

    def __str__(self):
        return self.name

apps/article/forms.py
from django.forms import Form, CharField


class SearchForm(Form):
    search = CharField()

apps/article/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from apps.article.models import Article, Tag


class HomeView(View):
    def get(self, request):
        articles = Article.published.order_by('-published_at')
        first = articles[0]
        articles = articles[1:]
        tags = Tag.objects.all()
        context = {
            "article": first,
            "articles": articles,
            "tags": tags
        }
        return render(request, "article/index.html", context=context)

    def post(self, request):
        search = request.POST.get('search')
        articles = Article.objects.filter(Q(title__icontains=search) | Q(category__name=search))
        if articles:
            first = articles[0]
            articles = articles[1:]
            tags = Tag.objects.all()
            context = {
                "article": first,
                "articles": articles,
                "tags": tags,
                "search": search
            }
            return render(request, "article/index.html", context=context)

        else:
            return HttpResponse(f"with {search} articles not found ")



class CategoryView(View):
    def get(self, request, pk):
        # category =Category.objects.get(id=pk)
        # articles = Article.objects.filter(category=category)
        articles = Article.objects.filter(category__id=pk)
        context = {
            "articles": articles,
            # "tags": tags
        }
        return render(request, "article/page.html", context=context)


class TagView(View):
    def get(self, request, pk):
        articles = Article.objects.filter(tags__id=pk)
        context = {
            "articles": articles,
        }
        return render(request, "article/page.html", context=context)


class ArticleView(View):
    def get(self, request, pk):
        article = Article.objects.get(pk=pk)
        return render(request, "article/article-page.html", context={"article": article})

templates/article/about.html
{% extends "base.html" %}

{% block content %}
    <div class="wrapper">   
  <!-- BEGIN body -->
  <div id="body">
    <!-- BEGIN content -->
    <div id="content">
      <!-- begin post -->
      <div class="recent post">
        <h2>About</h2>
        <p>This is an example of a WordPress page, you could edit this to put information about yourself or your site so readers know where you are coming from. You can create as many pages like this one or sub-pages as you like and manage all of your content inside of WordPress.</p>
      </div>
      <!-- end post -->
    </div>
    <!-- END content -->
    {% include 'sidebar.html' %}
  </div>
  <!-- END body -->
  <div class="break"></div>
</div>
{% endblock %}

templates/article/article-page.html
{% extends 'base.html' %}
{% block title %} ARTICLE DETAIL {% endblock %}

{% block content %}
    <div class="wrapper">
    <div id="body">
        <div id="content">
        <div class="recent post">
            <p><a><h1>{{ article.title}} </h1></a></p>
            <p>{{ article.body|safe }}</p>
            <p>
                Comments:<br>
            <p>-------------------------------------------------------------------------------------------------------------------------</p>
                    {% for comment in article.comments.all %}
                        Users:
                        {{ comment.owner }}<br>
                        {{ comment.body|safe }}
                    {% endfor %}
            </p>
        </div>
        </div>
    </div>
       {% include 'sidebar.html' %}
    <div class="break"></div>
</div>
{% endblock %}

templates/article/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="wrapper">
    <!-- BEGIN body -->
    <div id="body">
        <!-- BEGIN content -->
        <div id="content">
            <!-- begin recent post -->
            <div class="recent post">
                <h2 class="title">Recent News</h2>
                <h2><a href="{% url 'article:article-detail' article.id %}">{{ article.title }}</a></h2>
                <p>{{ article.body|safe|truncatewords:60}}</p>
            </div>
            <!-- end recent post -->
            <div class="posts">
                <!-- begin post -->
                {% for arct in articles %}
                    <div class="post">
                        <p class="date">{{ arct.published_at }}</p>
                        <h6><a href="{% url 'article:article-detail' arct.id %}">{{ arct.title|truncatewords:6 }}</a></h6>
                        <p>{{ arct.body|safe|truncatewords:20 }}</p>
                        <div class="details"><a href="{% url 'article:article-detail' arct.id %}">READ MORE</a> <a href="{% url 'article:article-detail' arct.id %}">{{ arct.comments.count }}
                            Comments</a></div>
                    </div>
                {% endfor %}

                <div class="break"></div>
            </div>
        </div>
        <!-- END content -->
        <!-- BEGIN sidebar -->
       {% include 'sidebar.html' %}
    </div>
    <!-- END body -->
    <div class="break"></div>
</div>
{% endblock %}

templates/article/page.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <div class="wrapper">
    <!-- BEGIN body -->
    <div id="body">
        <!-- BEGIN content -->
        <div id="content">
            <!-- begin post -->
            <div class="posts">
                <!-- begin post -->
                {% for arct in articles %}
                    <div class="post">
                        <p class="date">{{ arct.published_at }}</p>
                        <h6><a href="{% url 'article:article-detail' arct.id %}">{{ arct.title|truncatewords:6 }}</a></h6>
                        <p>{{ arct.body|safe|truncatewords:20}}</p>
                        <div class="details"><a href="{% url 'article:article-detail' arct.id %}">READ MORE</a> <a href="{% url 'article:article-detail' arct.id %}">{{ arct.comments.count }}
                            Comments</a></div>
                    </div>
                {% endfor %}
            <!-- end post -->
        </div>
        </div>
        {% include 'sidebar.html' %}
        
    </div>
    <!-- END body -->
    <div class="break"></div>
</div>
{% endblock %}